INSERT INTO USER (ID, USER_ID, PASSWORD) VALUES (1, 'tester','test');
INSERT INTO USER (ID, USER_ID, PASSWORD) VALUES (2, 'tester2','test');
INSERT INTO SCHEDULE (ID, CONTENT, DATE, TIME, USER_ID_ID) VALUES (1, '테스트', '2017-05-22','21-09-30','1')


